# Generated by Django 2.1.4 on 2018-12-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('2017-18', '2017-18'), ('2018-19', '2018-19'), ('2019-20', '2019-20'), ('2020-21', '2020-21'), ('2021-22', '2021-22'), ('2022-23', '2022-23'), ('2023-24', '2023-24'), ('2024-25', '2024-25')], max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('childid', models.CharField(max_length=9)),
                ('father', models.CharField(max_length=50)),
                ('cast', models.CharField(choices=[('st', 'ST'), ('sc', 'SC'), ('obc', 'OBC'), ('gn', 'GN')], max_length=4)),
                ('cast_name', models.CharField(max_length=50)),
                ('student_class', models.IntegerField()),
                ('brother_sister', models.CharField(max_length=50)),
                ('addmisstion_number', models.IntegerField()),
                ('school_entry_date', models.DateField()),
                ('chatravs', models.CharField(choices=[('Yes', 'yes'), ('NO', 'no')], max_length=5)),
                ('divyang', models.CharField(choices=[('Yes', 'yes'), ('NO', 'no')], max_length=5)),
                ('occupation_parents', models.CharField(max_length=50)),
                ('annual_income', models.IntegerField()),
                ('current_year_of_exam', models.DateField()),
                ('current_school_name', models.CharField(max_length=50)),
                ('result', models.DecimalField(decimal_places=2, max_digits=5)),
                ('aadhar_numer', models.IntegerField()),
                ('ifsc_code', models.CharField(max_length=50)),
                ('account_number', models.IntegerField()),
                ('portel_issued_ammount', models.IntegerField()),
                ('karmkar', models.CharField(max_length=50)),
                ('exp_date', models.DateField()),
            ],
        ),
    ]
