# Generated by Django 2.1.4 on 2018-12-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='aadhar_numer',
            field=models.CharField(max_length=12),
        ),
    ]
